version: "3"
services:
  app:
    image: python:3
    volumes:
      - .:/app
    working_dir: /app
    command: "bash docker/start_app.sh"
    ports:
      - 5000:5000

  linter:
    image: python:3
    volumes:
      - .:/app
    working_dir: /app
    command: "bash docker/start_linter.sh"

  test:
    image: python:3
    volumes:
      - .:/app
    working_dir: /app
    command: "bash docker/start_test.sh"